import { RootLayout } from '@nxify/kjd-ui-layout/server';
import '../index.css';

export const metadata = {
  title: 'Welcome to kjd',
  description: 'Generated by create-nx-workspace',
};

export default RootLayout;
